language: go
go:
  - 1.12.x
os:
  - linux
  - osx
dist:
  - stretch
  - buster
sudo: required
services:
  - docker
install: true
script:
  - env GO111MODULE=on make test
  - env GO111MODULE=on make acceptance-tests
